### PR TITLE
Remove the dead and broken EXTERNAL_MD5.

### PR DESCRIPTION
**Pull request by ivan-dives**
It was broken in 54c920e06ea5c6550b8fade9bfee8f3cb60a389f (fdupes-1.50-PR2):
fdupes.c:531: undefined reference to `getcrcpartialsignature'
fdupes.c:546: undefined reference to `getcrcpartialsignature'

Seing as noone cared to fix it for seven years I'm removing the dead broken code.

### CODE REVIEW

**Comment by adrianlopezroche** [comment]
Thanks.
